### ISSUE TITLE
Use Metropolis font for headings

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-blog#100]
A different font should be used for headings.

**Comment by muffinresearch** [comment]
Unless something changed recently, we're not using Metropolis on AMO, instead we're using Inter across the board. The [typography guidelines](https://mozilla.design/firefox/typography/) say "In cases that Metropolis is not available, Inter may be substituted for headlines as well."

Unless there's a compelling reason to use Metropolis, we can probably do the same for the blog for consistency and perf.

**Comment by willdurand** [comment]
> Unless there's a compelling reason to use Metropolis, we can probably do the same for the blog for consistency and perf.

One could say that the blog has its very own style so consistency doesn't seem to be at risk. For perfs, that might be true but I am not sure. For instance, given that we should only have en-US content, we could use the smaller Inter font size. blog.mozilla.org has 2 fonts, too.
