### ISSUE TITLE
Update header of the "blog" template (list of all blog posts)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-blog#107]
The header should looks like AMO, with less buttons/links:

<img width="627" alt="Screen Shot 2021-04-13 at 13 36 19" src="https://user-images.githubusercontent.com/217628/114546275-3cbf6580-9c5d-11eb-950b-648fb5b78bb9.png">

**Comment by vcarciu** [comment]
Verified as fixed in all major browsers: 
![blogheader](https://user-images.githubusercontent.com/1583842/115561941-b212e200-a2be-11eb-9002-44dec8832001.PNG)
