### ISSUE TITLE
Update favicons

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-blog#122]
The favicon files are missing. ~~Lets add them.~~ We only use `favicon.ico` on AMO so let's add this one only.

For QA: the favicon should be displayed and there shouldn't be a `404` in the network panel (devtools).

**Comment by vcarciu** [comment]
Verified as fixed : 
![favicon](https://user-images.githubusercontent.com/1583842/115564180-ea1b2480-a2c0-11eb-96c6-1c01ca3cab01.PNG)
