### ISSUE TITLE
Consider requiring a feature image in WP (or provide a default one)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-blog#124]
A blog post looks less nice when there is no featured image, and the list of blog posts looks odd, too:

<img width="1385" alt="Mozilla_Add-ons_Blog" src="https://user-images.githubusercontent.com/217628/114739154-eb8ca000-9d48-11eb-9fde-a25334645e32.png">

Let's see how we can best fix this problem. There is [a plugin to require a featured image](https://wordpress.org/plugins/require-featured-image/) but it isn't compatible with our WP version. There is also a plugin to set a default featured image: https://wordpress.org/plugins/default-featured-image/

**Comment by willdurand** [comment]
> There is also a plugin to set a default featured image: [wordpress.org/plugins/default-featured-image](https://wordpress.org/plugins/default-featured-image/)

I am going to give that plugin a try. It works on my local WP instance, which is similar to the WPEngine one.

**Comment by willdurand** [comment]
It should look like this now:

<img width="1552" alt="Screen Shot 2021-05-03 at 09 34 16" src="https://user-images.githubusercontent.com/217628/116851522-c9bd6500-abf2-11eb-8953-62b99a4ef4ab.png">

**Comment by ioanarusiczki** [comment]
@willdurand This is verified on https://addons.allizom.org/blog/ 

All cards have an associated image

![image associated](https://user-images.githubusercontent.com/33448286/117010933-2c216e80-aca2-11eb-9e4a-8e566f94a6db.png)
