### ISSUE TITLE
Header is a bit ugly on small screens (on real device)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-blog#132]
Portrait:

![signal-2021-04-16-103315_004](https://user-images.githubusercontent.com/217628/114996612-4afcc400-9e9f-11eb-9f19-b7388f68ddab.png)

Landscape:

![signal-2021-04-16-103315_003](https://user-images.githubusercontent.com/217628/114996623-4d5f1e00-9e9f-11eb-9207-5e43f4f23d49.png)

**Comment by ioanarusiczki** [comment]
@willdurand 

small screens: 

1. On Fenix - I see it looks good now.  Most of the page is Header, maybe a smaller header would look better but that's entirely subjective

![header in portrait](https://user-images.githubusercontent.com/33448286/115852739-41aeb280-a3dd-11eb-880b-d73012ac79c2.png)

![header in landscape](https://user-images.githubusercontent.com/33448286/115852927-76226e80-a3dd-11eb-8977-b2725154723a.png)

2. On other browsers - Chrome for Android, FF or Safari for iOS - the blog is not optimized for small view yet for the landing page https://addons-dev.allizom.org/blog/ Also I see issues with long unbroken strings inside the articles, if issues must be filed for these, let me know.

![Chrome for Android](https://user-images.githubusercontent.com/33448286/115853262-d6191500-a3dd-11eb-8360-cb894dc05644.png)

**Comment by willdurand** [comment]
> On other browsers - Chrome for Android, FF or Safari for iOS - the blog is not optimized for small view yet for the landing page [addons-dev.allizom.org/blog](https://addons-dev.allizom.org/blog/) Also I see issues with long unbroken strings inside the articles, if issues must be filed for these, let me know.

mm the screenshot does not look good indeed, is it Chrome of Safari?

**Comment by ioanarusiczki** [comment]
@willdurand On Android was Chrome
On iOS was FF and Safari
