### ISSUE TITLE
Update style as per UX feedback

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-blog#133]
From Slack:

A few more tweaks to consider for the blog:

```
figcaption {
 text-align: center;
}
body {
  font-size: 16px;
  line-height: 24px;
}
li {
  margin: 14px 0;
}
ul {
  margin: 14px 0;
}
p {
  margin: 14px 0;
}
main {
 padding: 40px 20px;
}
```

**Comment by willdurand** [comment]
`figcaption` is for the legend of an image for instance, like https://addons-dev.allizom.org/blog/2021/03/24/blog-post-lorem-ipsum-001/

**Comment by ioanarusiczki** [comment]
@willdurand header-title has a text-align:center property. This should be it.
