### ISSUE TITLE
Make static card "unavailable" when the add-on no longer exists (for some reasons)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-blog#134]
We generate "static" add-on cards at buildtime. We will need some JS to re-fetch the API at runtime (i.e. when we load the page) and if the add-on is no longer available (or error), we will update the card with a "unavailable" state.

The UI for this state was added in https://github.com/mozilla/addons-frontend/issues/10369 (screenshots included).

For QA: there is a card that has an invalid addon ID on this page: https://addons-dev.allizom.org/blog/2021/04/13/ipsumipsumipsumipsumipsumipsumipsumipsumipsumipsum-ipsumipsumipsumipsum/. It should be updated with the unavailable state.

Also note that this is a JS feature (client side) so, if JS is disabled, you should see the card without this state.

**Comment by willdurand** [comment]
> For QA: there is a card that has an invalid addon ID on this page: [addons-dev.allizom.org/blog/2021/04/13/ipsumipsumipsumipsumipsumipsumipsumipsumipsumipsum-ipsumipsumipsumipsum](https://addons-dev.allizom.org/blog/2021/04/13/ipsumipsumipsumipsumipsumipsumipsumipsumipsumipsum-ipsumipsumipsumipsum/). It should be updated with the unavailable state.

also cc @muffinresearch (for the post with cards that should be unavailable)

**Comment by vcarciu** [comment]
Verified as fixed using major browsers:
![missingaddon](https://user-images.githubusercontent.com/1583842/115569070-8f37fc00-a2c5-11eb-900c-b981cea2ab9e.PNG)
