### ISSUE TITLE
Use UAParser to set the correct app in the API call 

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-blog#138]
For QA: when browsing a page with a static add-on card, there should be an API call made. On Android, it should pass `app=android`, on all other OSes, it should pass `app=firefox`.

**Comment by vcarciu** [comment]
Verified as fixed on Android and other OSes:
Desktop:
![console](https://user-images.githubusercontent.com/1583842/115860350-08f0f680-a43a-11eb-98e9-f62ed1c36798.PNG)

Android:
![androidapp](https://user-images.githubusercontent.com/1583842/115860390-160de580-a43a-11eb-97b3-e2ffc54a1485.png)
