### ISSUE TITLE
Convert button in StaticAddonCard to an install button when UserAgent is Firefox

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-blog#140]
Static add-on cards should the "Download FF" button by default. When we are on Firefox, we should show a "Add to Firefox" button instead, a.k.a. an install button.

This issue is about show an install button instead of a download FF button when the browser is Firefox. Once this is done, install buttons should be disabled when:

1. it is Firefox for iOS
2. there is no current version for the add-on (or no download URL)

In theory, an install button could be disabled when the min/max version does not match or when it's not support by Fenix but this will be done in a different issue. After that, we should have the same behavior on the blog and on AMO frontend.

**Comment by willdurand** [comment]
> In theory, an install button could be disabled when the min/max version does not match or when it's not support by Fenix but this will be done in a different issue. After that, we should have the same behavior on the blog and on AMO frontend.

See: https://github.com/mozilla/addons-blog/issues/141 and https://github.com/mozilla/addons-blog/issues/142

**Comment by ioanarusiczki** [comment]
@willdurand 

1. on FF for iOS - "+Add to firefox" is disabled 

2.  for "there is no current version for the add-on (or no download URL)" the layout on Android or iOS looks the same, behind "This extension is not currently available"  the new-cta from the non-FF browser experiment is available. This perhaps should show the FF layout ?

![experiment layout](https://user-images.githubusercontent.com/33448286/115873439-cad2e300-a3f7-11eb-97cf-fc06dc17410c.png)

**Comment by willdurand** [comment]
>     1. on FF for iOS - "+Add to firefox" is disabled

ok, good

>     2\. for "there is no current version for the add-on (or no download URL)" the layout on Android or iOS looks the same, behind "This extension is not currently available"  the new-cta from the non-FF browser experiment is available. This perhaps should show the FF layout ?

it's fine to have the unavailable state on top of the download button, even for FF.
