### ISSUE TITLE
Disable install button when add-on is not compatible with the Firefox version (min/max)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-blog#142]
Once https://github.com/mozilla/addons-blog/issues/140 lands, we'll have to check the min/max version constraints when the browser is Firefox because some add-ons might not be compatible with it.

**Comment by ioanarusiczki** [comment]
@willdurand 

Maybe this could be tested by adding an addon with min and max lower than FF88 (a lang pack maybe) and then check that the button is disabled?

**Comment by willdurand** [comment]
> Maybe this could be tested by adding an addon with min and max lower than FF88 (a lang pack maybe) and then check that the button is disabled?

If you have an add-on in -prod that I can use, I can add it in one of the blogposts. I've been faking my user agent.

**Comment by ioanarusiczki** [comment]
@willdurand 

Then I tried the trick with Ghostery. Strict_min_version in the manifest is FF68 - I modified user agent to Mozilla/5.0 (Windows NT 10.0; rv:67.0) Gecko/20100101 Firefox/67.0 and I have an inactive button:

Would this be enough to confirm the compatibility check?

![checks](https://user-images.githubusercontent.com/33448286/117015368-530b8f00-acfa-11eb-81d1-2d3640e4cac5.png)

**Comment by willdurand** [comment]
> Would this be enough to confirm the compatibility check?

I think so, yes
