### ISSUE TITLE
Add support for `mozAddonManager` to install an add-on

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-blog#143]
We update the add-on cards to show an install button when the browser is Firefox and it supports the add-on. Currently, the button links to the XPI. When clicking the button, it downloads the XPI instead of starting the install process.

Let's use the power of `mozAddonManager` to install the add-on.

**Comment by vcarciu** [comment]
Verified as fixed with multiple available addons from https://addons-dev.allizom.org/blog/
