### ISSUE TITLE
Add breadcrumb in single post pages

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-blog#149]
We want to add a breadcrumb so that users can go to the list of all blog posts from a single post page.

**Comment by ioanarusiczki** [comment]
@willdurand On dev - the breadcrumb is displayed on all the pages available - the user can navigate to all articles now https://addons-dev.allizom.org/blog/ or to AMO homepage https://addons-dev.allizom.org/en-US/firefox/

![Breadcrumb](https://user-images.githubusercontent.com/33448286/116420768-f5cd9480-a846-11eb-852a-eaae69c6fce7.gif)

I did not see layout issues either. 

Verified on: Win10, Android and iOS
