### ISSUE TITLE
Hovering over More from the blog page should display the drop down menu

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-blog#157]
STR: 
Go to https://addons-dev.allizom.org/blog/ and hover over the "More" menu

Expected result:
The drop down menu should be displayed

Actual result:
menu is not visible - More must be clicked once 

![while hovering](https://user-images.githubusercontent.com/33448286/115392005-c4225100-a1e8-11eb-900c-34f7f68b80b0.gif)

**Comment by willdurand** [comment]
FTR: this is expected, it's a known limitation. The menu can only button with a click.

**Comment by ioanarusiczki** [comment]
@willdurand Verified on https://addons.allizom.org/blog/

![hover over fixed](https://user-images.githubusercontent.com/33448286/116998755-5b0e0380-ace7-11eb-8eee-9d0e2c407a57.gif)
