### ISSUE TITLE
RSS feed

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-blog#16]
Jorge mentioned this content should be consumed by Planet Mozilla, AFAIK  - that's typically handled by exposing a feed.

https://www.11ty.dev/docs/plugins/rss/ should be what's needed to provide this.

**Comment by willdurand** [comment]
I took a quick look. This plugin gives us a few filters but we still have to build the feed ourselves

**Comment by vcarciu** [comment]
I can see the atom feed with title "Mozilla Add-ons Blog RSS Feed". Marking issue as verified.
