### ISSUE TITLE
Check focus styles for keyboard navigation

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-blog#167]
If someone is using a keyboard for navigation (e.g. tabbing between links) it's important every element they can interact with has clear focus styling. 

A lot of this looks pretty good with default focus styles but there's a couple of places where there's something for hover and nothing for focus (e.g. install buttons).

* Test navigation with keyboard 
* Fix focus styles if they're missing.

**Comment by willdurand** [comment]
Thanks. The install button has its own style (from addons-frontend) so maybe AMO has a problem, too? (but maybe not)

**Comment by muffinresearch** [comment]
> Thanks. The install button has its own style (from addons-frontend) so maybe AMO has a problem, too? (but maybe not)

The install buttons on AMO look ok, but this might be because there's some generic focus styling that lives outside the button in some way.

**Comment by muffinresearch** [comment]
The "More..." dropdown in the header is another one that can't be visibly focused via the keyboard.

**Comment by willdurand** [comment]
> The "More..." dropdown in the header is another one that can't be visibly focused via the keyboard.

Looks like it is a problem on AMO as well.

**Comment by ioanarusiczki** [comment]
@willdurand Verified on https://addons-dev.allizom.org/blog/ 

On Firefox - the focus on the elements is less visible compared to Edge or Chrome but keyboard navigation is possible. 

More - with Firefox 

![focus on More](https://user-images.githubusercontent.com/33448286/117004385-dd240b00-ac9a-11eb-85be-ea1f5476e48e.png)

other elements wih Firefox

![other elements with ff](https://user-images.githubusercontent.com/33448286/117004799-57548f80-ac9b-11eb-9385-736b68b78140.png)
 

Chrome/Edge  - use a black rectangle 
![keyboard Chrome navigation](https://user-images.githubusercontent.com/33448286/117004230-b1088a00-ac9a-11eb-8b4c-9900c6791c8d.png)

For install buttons - on all browsers it looks the same: 

![focus on the download button](https://user-images.githubusercontent.com/33448286/117004597-165c7b00-ac9b-11eb-85ed-10ac03077c76.png)
