### ISSUE TITLE
Link post image as well as headings on blog homepage

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-blog#168]
Users often gravitate towards click larger targets such as images so it would be a good enhancement to link both the image and the heading for each post on the blog homepage. 

See https://blog.mozilla.org/ for an example of the link wrapping the image and the heading.

**Comment by willdurand** [comment]
This is annoying. I am not sure why I didn't implement it in the first place but I think it should be part of the MVP.

**Comment by ioanarusiczki** [comment]
@willdurand On dev https://addons-dev.allizom.org/blog/ I could navigate to the other pages using a click/tap on the image, click/tap on the Title and click/tap on "Read more" 
Tested with:
Firefox, Edge - Desktop
Fenix, Chrome - Android
Firefox, Safari - iOS

![redirecting](https://user-images.githubusercontent.com/33448286/116416879-6ffc1a00-a843-11eb-8d00-4d08c4203484.gif)
