### ISSUE TITLE
Layout issues on small screen devices on Safari

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-blog#176]
From https://github.com/mozilla/addons-blog/issues/132#issuecomment-825687454

Env. where this is reproducible: Chrome - Android 
iOS - Safari
IOS - Firefox 

Blog's landing page looks like this: 

![Chrome for Android](https://user-images.githubusercontent.com/33448286/115853262-d6191500-a3dd-11eb-8360-cb894dc05644.png)

Article pages - with long unbroken strings break the layout of the page 

![layout](https://user-images.githubusercontent.com/33448286/116386631-a2e1e600-a822-11eb-88e1-17101c308d99.png)

**Comment by willdurand** [comment]
> Chrome - Android

I cannot reproduce with Chrome on a real device.

The problem is "known" for Safari, though.

**Comment by ioanarusiczki** [comment]
@willdurand Hmm yes, this has been verified on Chrome with other Android devices 
Google Pixel 3a (Android 11)
Huawei Mate 20 Lite (Android 10)
OnePlus A3 (Android 6.0.1)
Galaxy S7 (Android 8.0.0)
Huawei (Android 10)

I have a Pixel first generation, I could not update Chrome so I made a device reset and tried again but still no success  - this is the only android device I could reproduce the layout issues above. 

![the only problem](https://user-images.githubusercontent.com/33448286/116401629-222be580-a834-11eb-8759-12cf624a66ba.png)

It seems to be an isolated case.

**Comment by ioanarusiczki** [comment]
@willdurand The issue described is no longer reproducible on iOS - FF and Safari 
or with Chrome - Android 

![right now on iOS](https://user-images.githubusercontent.com/33448286/117009229-5eca6780-aca0-11eb-9be1-6dcac8a88b6d.jpg)
