### ISSUE TITLE
Install button text should be "Install Theme" for static themes

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-blog#186]
The install button on AMO shows "Install Theme" for static themes. We should do the same on the blog.

**Comment by ioanarusiczki** [comment]
Verified on dev and stage - FF88 and Fenix

_Note:_ 
On blog the "+" from "Add to Firefox" or "Install Theme" is missing (I can't tell if that's expected) 

![Install Theme](https://user-images.githubusercontent.com/33448286/116993441-2a769b80-ace0-11eb-999e-124e8a9d3f1d.png)

**Comment by willdurand** [comment]
>  On blog the "+" from "Add to Firefox" or "Install Theme" is missing (I can't tell if that's expected)

That's a good question. I think it is expected because I remember a discussion about removing `+` on those buttons, but it isn't consistent with AMO so maybe we should have them...

@ioanarusiczki could you please create an issue for that? Thanks!

**Comment by ioanarusiczki** [comment]
@willdurand Done https://github.com/mozilla/addons-blog/issues/191

**Comment by willdurand** [comment]
> @willdurand Done #191

Thanks!
