### ISSUE TITLE
Install button should be disabled on Fenix when add-on is not an extension

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-blog#187]
This is similar to what we do on AMO: only (recommended) extensions are supported on Fenix.

**Comment by ioanarusiczki** [comment]
@willdurand Static theme - button is disabled. Verified on Fenix with Android 10

![theme on Android](https://user-images.githubusercontent.com/33448286/116992670-14b4a680-acdf-11eb-9621-f974a7c8baf5.png)
