### ISSUE TITLE
Fonts on Edge or Chrome are less visible compared to Firefox - on desktop 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-blog#190]
This is with Edge/Chrome 

![with Chrome](https://user-images.githubusercontent.com/33448286/117009726-eadc8f00-aca0-11eb-9898-7161ec82d20e.png)

This is with FF88

![on Firefox](https://user-images.githubusercontent.com/33448286/117009886-0fd10200-aca1-11eb-9f6a-3259f99687df.png)

**Comment by willdurand** [comment]
Which OS and which browser version? I cannot reproduce on a side-by-side comparison.

**Comment by ioanarusiczki** [comment]
@willdurand It is Windows - 
![Edge](https://user-images.githubusercontent.com/33448286/117010533-bf0dd900-aca1-11eb-9a50-34da8ee2a4b9.png)

![Chrome](https://user-images.githubusercontent.com/33448286/117010552-c339f680-aca1-11eb-9cb7-b6e50847251e.png)

It is probably not reproducible with MacOS

**Comment by willdurand** [comment]
Right, I can see the text slightly lighter on Chrome/Edgium on Windows but there is nothing wrong, it's just how Chrome draws the font and text. We can see the same behavior on AMO as well (on a detail page with enough content). In other words, I am not sure there is anything we can do.

**Comment by willdurand** [comment]
As per the comment above, this is expected.
