### ISSUE TITLE
Add "+" to the install buttons 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-blog#191]
Followup for https://github.com/mozilla/addons-blog/issues/186#issuecomment-831902777

Right now on the blog: 

![ux for the button](https://user-images.githubusercontent.com/33448286/117012186-5b15ff80-acf7-11eb-868c-1ada30856ec0.png)

On AMO:

![the plus](https://user-images.githubusercontent.com/33448286/117012333-839df980-acf7-11eb-89a2-60259ac4a4c9.png)

This is reproducible for themes too.

**Comment by bobsilverberg** [comment]
I recall a discussion with UX that there was a desire to remove these + signs everywhere, so that's probably why they've been left off the blog. Maybe what we need is an issue on addons-frontend to remove them from there as well?

**Comment by willdurand** [comment]
> I recall a discussion with UX that there was a desire to remove these + signs everywhere, so that's probably why they've been left off the blog. Maybe what we need is an issue on addons-frontend to remove them from there as well?

Yes, exactly. I still see "+" signs on `about:addons` in Nightly, though.

**Comment by willdurand** [comment]
I got confirmation from UX and Product: we don't want the plus sign anymore.
