### ISSUE TITLE
Add safe filter to content in Atom feed

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-blog#192]
This is needed because the filter we are using (from RSS plugin) marks the content as safe (i.e. disables auto-escaping).

**Comment by ioanarusiczki** [comment]
@willdurand Not sure how to check on this. Could you add some STR?

**Comment by willdurand** [comment]
> @willdurand Not sure how to check on this. Could you add some STR?

You can make sure than the Atom feed is available and it can be viewed in a client if possible.

**Comment by ioanarusiczki** [comment]
@willdurand 
From:
<link rel="alternate" type="application/atom+xml" title="Firefox Add-on Reviews RSS Feed" href="/blog/feed.xml">

I used SharpReader on Windows to view the feed https://addons.allizom.org/blog/feed.xml 

I can see the blog posts - titles and content. One thing noticed that the addon cards are not present, is that expected? 

![feed displayed](https://user-images.githubusercontent.com/33448286/117646604-9ea7b800-b194-11eb-86b2-6cc0509bf453.png)

Only on one page I see some addon card content (those currently unavailable):

![A card displayed](https://user-images.githubusercontent.com/33448286/117647983-5a1d1c00-b196-11eb-8b4e-73ec6e3118ab.png)
