### ISSUE TITLE
There's no custom 404 page if the url under /blog/ doesn't exist

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-blog#194]
See https://addons-dev.allizom.org/blog/whatever/

<img width="837" alt="404_Not_Found" src="https://user-images.githubusercontent.com/1514/117189314-f8476580-add5-11eb-8ce1-e4aeb44bf068.png">

**Comment by willdurand** [comment]
On the screenshot, I am seeing a second error about "error.html" so maybe we could build a custom 404 in this repo, which would generate an `error.html` page, and that's how we could implement a custom 404? (just a guess)

**Comment by willdurand** [comment]
@muffinresearch it isn't super pretty but it does the job: https://addons-dev.allizom.org/blog/whatever/

**Comment by ioanarusiczki** [comment]
@willdurand 

Verified on https://addons-dev.allizom.org/blog/

![404](https://user-images.githubusercontent.com/33448286/117454529-e937f300-af4e-11eb-9e75-b2168417eacd.png)
