### ISSUE TITLE
robots.txt currently prevents indexing 

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-blog#2]
This is a reminder to change this before this site goes live.

**Comment by willdurand** [comment]
I think we will simply `rm` the file during the deployment.

**Comment by ioanarusiczki** [comment]
@willdurand I could use some str for qa. 
Thanks

**Comment by ioanarusiczki** [comment]
@willdurand 

As discussed, http://amo-blog-prod.s3-website-us-west-2.amazonaws.com/blog/robots.txt is a 404 right now - it works as intended.
