### ISSUE TITLE
Blog Sitemap requirements

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-blog#204]
On AMO a sitemap is being generated by Django. For the blog we will probably want to create a sitemap as part of the build and then ensure that is linked to from the sitemap in the root of the site.

This issue is to figure out what we need and consider how it should work.

**Comment by muffinresearch** [comment]
I spoke to @eviljeff about this. Once there's a sitemap provided by the blog we can file an issue on addons-server so its url can be added to the main sitemap.

**Comment by ioanarusiczki** [comment]
@willdurand with https://addons.allizom.org/blog/sitemap.xml?debug I see the following xml file:

![tree file](https://user-images.githubusercontent.com/33448286/122055693-be3a8d80-cd9d-11eb-955a-7d8e9f7aa742.png)
