### ISSUE TITLE
Use blog name in the breadcrumbs

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-blog#217]
Currently, the breadcrumbs say Blog instead of the blog name (Firefox Add-on Reviews).

**Comment by willdurand** [comment]
> Currently, the breadcrumbs say Blog instead of the blog name (Firefox Add-on Reviews).

@jvillalobos could you file an issue in addons-frontend to adjust the name of the blog there as well?

**Comment by jvillalobos** [comment]
Done, thanks. https://github.com/mozilla/addons-frontend/issues/10645

**Comment by ioanarusiczki** [comment]
@willdurand Verified on AMO dev - FF89(Win10). 

![breadcrumb](https://user-images.githubusercontent.com/33448286/121176130-b82e3500-c810-11eb-9fff-3b14e0126860.png)
