### ISSUE TITLE
Don't include dates in blog URLs

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-blog#218]
Instead of `/blog/2021/04/20/best-adblockers-firefox-2021/`, let's just do `/blog/best-adblockers-firefox-2021/`

**Comment by ioanarusiczki** [comment]
@willdurand Dates have been removed from the URL

![no dates](https://user-images.githubusercontent.com/33448286/121342112-31dc2680-c8d6-11eb-9b6b-ce55c39579bd.png)
