### ISSUE TITLE
Get FF banner should be displayed on the index page only

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-blog#228]
From https://github.com/mozilla/addons-frontend/issues/10657#issuecomment-856037531

1. The non-FF yellow banner should be available on this page: https://addons-dev.allizom.org/blog/

The banner on AMO homepage: 

![homepage](https://user-images.githubusercontent.com/33448286/121163466-a98d5100-c803-11eb-8131-f5068395789e.png)

**Comment by willdurand** [comment]
@jvillalobos the content of the notice (see screenshot above) does not really work for the blog index. There is no add-ons listed there so either we have new content (and it is a new notice that we don't have elsehwere) or we forget about this feature (that would likely be the only page without a notice on AMO so I guess that's fine). WDYT?

**Comment by willdurand** [comment]
> I don't think we should special case the text for one page. The user is in the add-ons site, as evidenced by the site name and top nav, so it shouldn't be too surprising that we would show that notice. I think it's fine to have it as is.

So are we good with a notice that says "to use these add-ons [...]"  on a page that won't have any add-ons listed? Other pages on AMO don't have this problem because they all have 1 or more add-ons listed.

**Comment by bobsilverberg** [comment]
If I can jump in here, I think what we're suggesting is that we simply don't show the banner at all on the blog home page, as opposed to showing it with special text. That would also eliminate a bunch of extra code that Will had to write to make it appear on only the blog home page. Does that seem reasonable, or do we feel it's really important to have the banner on the blog home page?

**Comment by jvillalobos** [comment]
If the argument is that showing the banner on this one page is a maintenance burden, then I'm okay with dropping this. I wouldn't expect this to be a particularly popular page anyway.

**Comment by willdurand** [comment]
Ok then we wontfix this issue.
