### ISSUE TITLE
Deploy to production

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-blog#231]
Update: the milestone is set to 2021.06.17 but we soft-launch on June 15th.

---

We are able to deploy to -dev and -stage. In order to deploy to production, we need to:

- [x] add env variables in Circle CI with the production config
- [x] update our Circle CI config to deploy a tag to production
- [x] fix https://github.com/mozilla/addons-blog/issues/2
- [x] update nginx config to proxy `/blog/`

**Comment by willdurand** [comment]
@bqbn could you please add the environment variables in circle? I can update the circle config myself.

Also, I suppose we could deploy to production earlier as long as we don't remove [this nginx condition](https://github.com/mozilla-services/cloudops-deployment/blob/fefca5505db43f9f3c0ca8ea28844ea6d0306f15/projects/amo/puppet/modules/amo_proxy/templates/nginx.addons.conf.erb#L337)?

**Comment by bqbn** [comment]
> @bqbn could you please add the environment variables in circle?

Good news! They're already there.

> Also, I suppose we could deploy to production earlier as long as we don't remove [this nginx condition](https://github.com/mozilla-services/cloudops-deployment/blob/fefca5505db43f9f3c0ca8ea28844ea6d0306f15/projects/amo/puppet/modules/amo_proxy/templates/nginx.addons.conf.erb#L337)?

Correct!

**Comment by willdurand** [comment]
> Good news! They're already there.

Ha thanks, I did notice env vars without any prefix but didn't actually parse them, I thought they were used for something else :D Thanks!

> Correct!

Good, I'll push some files to the S3 bucket ASAP then.

**Comment by willdurand** [comment]
@bqbn I deployed some content to prod and it worked as expected, please do NOT update the Nginx config yet. We'll do that next Tuesday when we'll have the final content. Thanks!

**Comment by willdurand** [comment]
I pushed the content on the prod S3 bucket. We only need to remove the nginx condition for prod to be able to serve the blog.

**Comment by willdurand** [comment]
deployed!

**Comment by ioanarusiczki** [comment]
@willdurand 
https://addons.mozilla.org/blog/ can be accessed - verified with Win10, Android, iOS - FF, Chrome, Safari

![deploy to prod](https://user-images.githubusercontent.com/33448286/122190330-918e8080-ce46-11eb-8258-3e11a2a4dbd2.gif)
