### ISSUE TITLE
Add border and/or box shadow to images

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-blog#236]

**Comment by ioanarusiczki** [comment]
@willdurand I see a border/shadow around the image on https://addons.allizom.org/blog/translate-the-web-easily-with-a-browser-extension/

It is very discrete, almost invisible on the left and right, the upper part does not seem to have a border, I hope it's ok. 

On FF89:

![image](https://user-images.githubusercontent.com/33448286/122047746-56804480-cd95-11eb-8e3f-6f4248d1c108.png)

On Chrome - hardly visible (but brightness of the screen was at 80%):

![on Chrome](https://user-images.githubusercontent.com/33448286/122048457-1ff6f980-cd96-11eb-8790-ee3a0945d545.png)

On Android with 100% brightness:

![Android with full brightness](https://user-images.githubusercontent.com/33448286/122049250-10c47b80-cd97-11eb-9126-8b73de0653db.png)
