### ISSUE TITLE
Remove syntax hightlighting

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-blog#24]
@muffinresearch I see we have a plugin and some (s)css files for syntax highlighting. Is this needed for the blog?

**Comment by muffinresearch** [comment]
If this is never going to feature developer related content, which seems to be where we're going then no, but it might be good to check with Jorge just in-case.

**Comment by willdurand** [comment]
ping @jvillalobos

**Comment by jvillalobos** [comment]
I don't expect us to feature code in the blog, so I think we can do without this.

**Comment by willdurand** [comment]
ok, let's remove the config for now then. We can re-add it later if needed./
