### ISSUE TITLE
Remove underline from headers that are also links

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-blog#241]
If a header is also a link, don't underline it. The color should be enough to indicate that it's also a link.

**Comment by willdurand** [comment]
This is how it looks right now FWIW:

![Screenshot 2021-06-16 at 10 58 40](https://user-images.githubusercontent.com/217628/122190107-d12e8a00-ce91-11eb-9b00-62ba6cf108ee.png)

**Comment by ioanarusiczki** [comment]
@willdurand 
"Simple Translate" at 32px - is not a link, it's simple text. 

![headers](https://user-images.githubusercontent.com/33448286/122564785-9c8a1200-cffa-11eb-81ea-4639939155ee.png)

From https://github.com/mozilla/addons-blog/pull/247 it looks like it should be a blue URL.

**Comment by willdurand** [comment]
>  "Simple Translate" at 32px - is not a link, it's simple text.

The problem is: we use prod data in all envs. I had to update the heading manually using the devtools.

**Comment by ioanarusiczki** [comment]
@willdurand 

I edited locally HTML content, and this is the result:

![Simple Translate](https://user-images.githubusercontent.com/33448286/122905841-6c968380-d306-11eb-9ba9-04f9b19f4f31.png)
