### ISSUE TITLE
Add spacing above and below images

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-blog#242]
Like the main mozilla blog, let's add spacing above and below images so the content doesn't look so dense.
This is how it currently looks:
![Screenshot 2021-06-14 at 12-24-42 Translate the web easily with a browser extension - Firefox Add-on Reviews](https://user-images.githubusercontent.com/62568/121940609-884cc900-cd0b-11eb-9394-531130ae1844.png)
The main mozilla blog seems to add about one line of spacing above and below all images, which makes it look less busy.

**Comment by ioanarusiczki** [comment]
@willdurand 
Verified on https://addons-dev.allizom.org/blog/ with FF89(Win10). 

![margin40px](https://user-images.githubusercontent.com/33448286/122041235-93483d80-cd8d-11eb-8cf5-ca17a8cd7cf0.png)
