### ISSUE TITLE
'More' popup menu in the header has invisible text on first show

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-blog#245]
the 'More' popup menu in the blog header, that shows links to "Dictionaries & Language Packs", "Firefox Add-on Reviews", "Add-ons for Android", momentarily* doesn't have visible links the first time the user hovers over the link and the div is visible.  This is because the font file used for the links isn't used elsewhere on the page so it's loaded on demand at that point.
*(your moment may vary depending on your internet connection speed.  a second of so for me; longer for slower connections)

There are a number of solutions (e.g: preload all the fonts; reduce the number of variants; use a single font with all the weights; add css to fallback to an OS font; etc)

For QA: in addition to the problem stated above, the patch that fixes this issue changes the way we serve fonts, which is similar to what we are doing on AMO (subset font, etc). Please make sure that we have a subset font preloaded and only the subset is used for now.

**Comment by ioanarusiczki** [comment]
@willdurand 

- More menu with cache disabled - after reload - loads immediately:

![more solved](https://user-images.githubusercontent.com/33448286/122208919-c7d4fb80-ce58-11eb-8dd8-7df4d92850f7.gif)

2. 
- .woff font packages with cache disabled load the Inter-roman subset twice of 30.97 KB and one more package of 155KB

![twice a subset](https://user-images.githubusercontent.com/33448286/122209195-1d110d00-ce59-11eb-8767-f31c42ab4093.png)

- with cache enabled, one subset is loaded only, of 30.22 KB

**Comment by ioanarusiczki** [comment]
@willdurand 

As discussed, this is a devtools bug. - I could reproduce it only with FF (Chrome and Edge show the package once). 

Verified on AMO stage - FF89(Win10). 

![verified with Edge](https://user-images.githubusercontent.com/33448286/122226310-b72d8100-ce6a-11eb-94c9-923fa4b2508b.png)
