### ISSUE TITLE
Consider treating links to AMO pages as external links

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-blog#249]
As discussed on Slack, any links to AMO (e.g., to search results, user profile pages, add-on detail pages, etc.) on the blog are currently treated as internal links and therefore cause a user to "leave" the blog (i.e., they open in the same tab).

We might not want users to leave the blog, so we might want to open these links in a new tab, as we generally do for external links.

Discuss. 😄

**Comment by willdurand** [comment]
cc @jvillalobos

**Comment by jvillalobos** [comment]
IMO they are internal links and shouldn't open in a new tab. Our goal is to get those users to either install something from the blog page or to move on to navigate to AMO, so there shouldn't be much loss in someone not reading an entire article. There's always the back button :P

**Comment by eviljeff** [comment]
product hath spoken
