### ISSUE TITLE
Add blog feed to Planet Mozilla

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-blog#259]
We should syndicate our posts on Planet Mozilla for added visibility. I'm not sure if we already have a feed we can submit, so setting one up is possibly the first step. The documentation for adding a new feed can be [found here](https://wiki.mozilla.org/Planet_Mozilla).

**Comment by willdurand** [comment]
@jvillalobos here is the feed if you want to file the bug, but please also ping mhoye because he doesn't actively look at these bugs AFAIK: https://addons.mozilla.org/blog/feed.xml

**Comment by jvillalobos** [comment]
Great! I filed [the bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1719504) and pinged mhoye. I don't think we need to track this here.
