### ISSUE TITLE
Fix title size on small screens

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-blog#262]
On small-ish screens, the title is too big and causes the end of the title to be
hidden behind the content. This is mainly because editorial uses rather long
titles so we need to fix the problem by reducing the font-size.

**Comment by ioanarusiczki** [comment]
@willdurand I verified on AMO dev with Android. Looks good to me 👍 

![lgtm](https://user-images.githubusercontent.com/33448286/126337626-5d1d0c97-040d-4a3c-acde-6ff0319331e5.png)
