### ISSUE TITLE
Article layout has issues on Safari 

### ISSUE THREAD

**Issue by rik** [mozilla/addons-blog#272]
The areas highlighted are wrapping too much.

![addons-safari](https://user-images.githubusercontent.com/3653/127208289-91f43106-f52d-445b-928b-3fc28f64a2e4.png)

**Comment by willdurand** [comment]
heh, there seems to be a problem with `inline` vs `inline-block` in Safari.

**Comment by ioanarusiczki** [comment]
@willdurand 
I could not reproduce it on AMO stage on Safari. At a quick look, it wasn't reproducible on prod either.  
On FF or Chrome - looks good.

**Comment by willdurand** [comment]
>  I could not reproduce it on AMO stage on Safari. At a quick look, it wasn't reproducible on prod either.

Sorry I thought I mentioned it but we deployed this change to -prod by mistake (on Tuesday...)

**Comment by ioanarusiczki** [comment]
@willdurand Good to know. That explains it !
