### ISSUE TITLE
Switch `addons-frontend-blog-utils` dep back to the latest npm version

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-blog#299]
We implemented a change to update this lib while the npm registry was down. Let's revert this change to use npm versions when npm becomes available again.

---

For QA: please make sure we can install add-ons (or buttons are not disabled at least)

**Comment by ioanarusiczki** [comment]
@willdurand 
- I've been going through the articles on https://addons-dev.allizom.org/blog/ and all install addons were active. Using `extensions.webapi.testing` set to true, I could install addons without errors. FF92(Win10)
- I could install all compatible Android addons with Android 10.0 from https://addons-dev.allizom.org/blog/ : LeechBlock, Tomato Clock, YouTube High Definition, Search by Image, Decentraleyes, Ghostery, AdGuard AdBlocker, Privacy Badger, uBlock Origin.
