### ISSUE TITLE
Use the proper API for each environment

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-blog#308]
This is a follow-up to https://github.com/mozilla/addons-blog/issues/298.

We should be using the dev API for the dev instance of the blog, and the stage API for the stage instance of the blog. One complication is that we'll want the add-ons for an article to work in each environment, but the `id`s are not currently in sync.

Ideally we should be using `guid` for this, as opposed to `addonId`, because the latter is the primary key to a table and therefore more difficult to change.

We need to check the code to see what is currently being used, and if it is currently `addonId` look into how difficult it would be to change it to use `guid` instead.

**Comment by eviljeff** [comment]
> As I mentioned elsewhere, the add-on ID as in "AMO pk" seems to be the only ID that won't changed in 4 years or so because AFAIK GUIDs can get reused (I don't exactly know the details, though) and slugs can also be updated and/or reused as well.

GUIDs can't be changed by the developer, or reused by a different developer even after an add-on is deleted.  A GUID can be reused by _the same_ developer if they deleted their add-on for an entirely different extension, but they could do that with a new version anyway.  (Slugs though, yep, they can be changed and reused at any time.)

(I didn't realize the discussion had continued here before I replied in the other issue)

**Comment by eviljeff** [comment]
yeah, a developer could upload a new xpi to an existing listing (`id`) that is a completely different add-on and/or change the metadata on AMO entirely (name, description, icon, etc).  They could transfer ownership of the add-on to a different user too.

There are only a few more restrictions on a new version v.s deleting and starting again: that the version number isn't reused (not relevant to the risk here), and the add-on type can't change (only really a potential risk if we're blogging about types that are more restrictive than an extension, like a theme, I would have thought).

imo, if we're really worried about the risk of add-ons changing significantly after they're featured in the blog we'd be better tagging them with one of the promoted groups, e.g. Strategic (it's not badged, but it enforces `admin_review=True`).  (Spotlight would be my choice but it also enforces `warning=False`, which would hide the warning label on frontend, and `pre_review=True, admin_review=True,` which might be undesirable when queue times are long.)

**Comment by ioanarusiczki** [comment]
@bobsilverberg That's great, it means qa can check addon installs at release testing from now on. 
 Looking now at the -dev blog on articles I think there's still prod addons displayed , I just added `extensions.webapi.testing` and I installed one.
Could you add some steps here for us?

**Comment by bobsilverberg** [comment]
> @bobsilverberg That's great, it means qa can check addon installs at release testing from now on but looking now at the -dev blog on articles I think there's still prod addons displayed , I just added `extensions.webapi.testing` and I installed one. Could you add some steps here for us?

Unfortunately it's not quite working yet. #351 needs to land in order to make the deploy to dev work to use the dev API.  Once that's working, all of the add-on cards on the dev blog will be populated using the dev API, which means that most of them will show the "add-on not found" message, as the `addonId` used in the blog post won't exist in the dev database. In order to be able to properly test on dev we'll need to update one of the articles in the blog to use the `guid` instead of the `addonId` to identify the add-ons for the cards, and then we'll need to make sure that the add-ons in dev have the same `guid` as those in prod (for that article).

@devaneymoz Would you be able to update one of the articles (maybe an older one, in case we run into temporary issues) to use the `guid` of the add-on instead of the `id` of the add-on in each card? After that's done, I think that QA could ensure that we have matching add-ons in dev with the same `guid`.

**Comment by bobsilverberg** [comment]
@ioanarusiczki The deployment issue has been fixed, which means the dev version of the blog is now using the dev API. This does mean, however, as discussed above, that the add-on cards on dev all show "This extension is not currently available." because the dev API is being used with non-existent add-on ids. I will ping Scott to see if we can get an article updated to use guids instead, and then perhaps you can make sure that dev has the expected guids.

**Comment by ioanarusiczki** [comment]
@bobsilverberg Yes, I see "This extension is not currently available." on dev so sure, ping me back. 
It would be great to have some addons compatible with Android too for -dev/stage.

**Comment by willdurand** [comment]
> This does mean, however, as discussed above, that the add-on cards on dev all show "This extension is not currently available." because the dev API is being used with non-existent add-on ids.

Something is off: if I disable JavaScript, I can see the static add-on cards but when JS is enabled, the dynamic cards are in a disabled state (the message saying "extension is not currently available").

**Comment by ioanarusiczki** [comment]
@bobsilverberg There hasn't been an update on this issue in a while. Could you help with the addon cards?
