### ISSUE TITLE
CSP should allow a.m.o/user-media/ and not use the old CDN

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-blog#326]
### Describe the problem and steps to reproduce it:

1. Go to the blog (any env), e.g., https://addons-dev.allizom.org/blog/how-to-choose-the-right-password-manager-browser-extension/ (-dev)

### What happened?

No more add-on icons. Plenty of CSP errors in the console.

### What did you expect to happen?

Icons should be displayed. No CSP errors.

### Anything else we should know?

We deployed a change on Monday, which caused this problem because the CSP in this project haven't been updated.

**Comment by ioanarusiczki** [comment]
@willdurand Looks good to me now 

![no csp errors](https://user-images.githubusercontent.com/33448286/139861746-e6289ea0-ae70-4881-8551-62924efee272.png)
