### ISSUE TITLE
Consider hiding header menu items on the blog

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-blog#331]
### Describe the problem and steps to reproduce it:

1. Load AMO on mobile - the site url should be https://addons-dev.allizom.org/en-US/android/
2. Open the blog - https://addons-dev.allizom.org/blog/
3. Click on Themes in the header menu
4. Verify the landing page

### What happened?
You land on https://addons-dev.allizom.org/en-US/android/themes/ but, since there are no Themes available for mobile, the page is populated with extensions while the page and shelf titles are referencing "themes":
[header menu on blog]
![image](https://user-images.githubusercontent.com/31961530/139818324-c2e30bea-34e2-44f0-9068-30d64170d017.png)
[landing page after clicking on themes]
![image](https://user-images.githubusercontent.com/31961530/139818638-5f41378a-2eca-4e3d-8c12-572d17e232a8.png)

### What did you expect to happen?
Maybe we should not show the header menu items on the blog at all. Users can click on the page logo if they want to navigate to the addons site.

### Anything else we should know?
- on the frontend, the header menu items are hidden by default:
![image](https://user-images.githubusercontent.com/31961530/139818746-3357b9c3-9bfd-41d9-9309-4d3571417e22.png)

- The underlying issue will still be present on the frontend, but users will be able to land on that page only by manually changing the url.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDBLOG-10)

**Comment by diox** [comment]
I agreed that on Android we should probably hide the menu like we do on frontend. I filed https://github.com/mozilla/addons-frontend/issues/11331 for the underlying issue.

**Comment by ioanarusiczki** [comment]
@willdurand 

Verified on AMO dev with Fenix 119.0 

Clicking the Logo would redirect to Android's extension homepage:  https://addons-dev.allizom.org/en-US/android/

![no themes](https://github.com/mozilla/addons-blog/assets/33448286/5d698346-1e96-4da5-8110-1e43c5859092)
