### ISSUE TITLE
Relax the regex for addonId

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-blog#342]
This is a spin-off from https://github.com/mozilla/addons-blog/issues/308.

In order to be able to test the blog with the dev API, we need to have a post with add-on identifiers in it that match add-ons on both prod and dev. Currently, prod uses the `id` of the add-on, but we cannot force-create an add-on on dev with a matching `id`, so we would need to use the `slug` or `guid` on dev to match the identifier used in the post. Our code will work if the `slug` or `guid` is used as an identifier in the post, so the easiest way to deal with this is to update a post to use `guid`s instead of `id`s, and then create/update add-ons on dev that have the same `guid`s.

There is currently a regex in [`filters.js`](https://github.com/mozilla/addons-blog/blob/main/src/filters.js#L87) which only allows numeric identifiers right now, so we need to relax that to allow basically any single word. After doing that, a post can be updated to use `guid`s, and then we can set up dev to allow us to test a post with the dev API.

**Comment by ioanarusiczki** [comment]
@bobsilverberg In case this can be verified by qa please let me know.

**Comment by bobsilverberg** [comment]
@ioanarusiczki With the current environments available, I don't think this will be feasible to test.
