### ISSUE TITLE
Update circle config to build the dev version of the blog using the dev API

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-blog#351]
https://github.com/mozilla/addons-blog/issues/308 landed, which allows the dev version of the blog to use the dev API, but unfortunately the code to build and deploy the dev version is not using the correct environment variable so it isn't currently working.

We need to change the circle CI config to make sure the the `AMO_BASE_URL` env var is set to `https://addons-dev.allizom.org` when the dev version of the blog is being built.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I don't think there's anything I can do until addons appear on -dev as discussed into https://github.com/mozilla/addons-blog/issues/308
