### ISSUE TITLE
Fix broken integration test

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-blog#354]
There is an integration test that has `https://addons.mozilla.org` hardcoded into it for the base URL of the blog, but with the landing of https://github.com/mozilla/addons-blog/issues/351, the dev version of the blog is now being built using `https://addons-dev.allizom.org` so the test needs to make use of the environment variable in order to look for the correct URL.

See https://app.circleci.com/pipelines/github/mozilla/addons-blog/2859/workflows/d3e3fee4-1fdb-4f1d-9e25-04f2fdbbf403/jobs/6171 for an example failure.

**Comment by willdurand** [comment]
heh,that's unfortunate because the integration test was meant to verify the prod content. I guess that's fine, though.

**Comment by bobsilverberg** [comment]
> heh,that's unfortunate because the integration test was meant to verify the prod content. I guess that's fine, though.

It should still be able to do that when running against the stage and prod environments though, right?

**Comment by willdurand** [comment]
oh, right
