### ISSUE TITLE
"More..." link needs two taps to open the menu after page load on Android

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-blog#369]
## STR

With Firefox for Android:

1. Open addons-dev.allizom.org/blog/
2. Tap the "More..." menu

## What happened?

The menu isn't revealed. Another tap is necessary.

## Expected

The menu is shown.

## Other information

After that, it's possible to open/close the menu with a single tap. It's only after a full page load, and only the very first time.

Also reproducible on Chrome for Android (and in Chrome Desktop in "responsive mode").

**Comment by ioanarusiczki** [comment]
@diox @willdurand 

I checked this behavior on [-dev](https://addons-dev.allizom.org/blog/) and [-stage ](https://addons.allizom.org/blog/) and at a full load the More Menu is open when tapping it the first time. 

Verified on Android 10.0
