### ISSUE TITLE
Investigate scheduled posts (and updates)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-blog#4]
We would like to schedule posts in an automated manner.

To provide scheduling we will need to either (non-exhaustive list):

- Build the blog at daily intervals.
 	- Without checking if we need to do this would be inefficient.
- Poll wordpress to check for new posts or other changes before building.
	- Checking for new posts is easy, (Make a HEAD request and read the header for the post count) but updates for deeper content is less viable.
- Have some way to schedule posts based on knowing what content is pending.
	- Can wordpress call a webhook for scheduled content? We could potentially set this up based on cronjob.

**Comment by willdurand** [comment]
I believe this is relevant only if the blog is not a throwaway experiment and/or we have lots of articles to schedule for the "pilot".

@muffinresearch would you have some more info about that?

**Comment by muffinresearch** [comment]
@willdurand Talking to Jorge about this last week, he would like us to have the blog work as smoothly as possible. The project *is* a test from the perspective of trying something and measuring what impact it has. As with any test there's a chance if it didn't show the expected value it might be something we don't continue with, but one could argue that is true of nearly everything we do.

For any of these issues Jorge would be happy to look at and provide input re: priority. I'd suggest we do that once most bugs are filed. For example we probably should prioritize something that has a reasonable temporary (manual) workaround lower than another feature that doesn't have a workaround.

Where it makes sense, I'd suggest we aim for the simplest pragmatic solution that gets things working with the option of future refinements later.
