### ISSUE TITLE
"SEO tags" for the `/blog/` page (list of blog posts)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-blog#47]
In #10, we added Yoast SEO tags to the article pages. We could probably add some metadata on the blog index page as well (`/blog/`).

**Comment by willdurand** [comment]
@jvillalobos we'd need some content here, at least:

- default title of the blog (currently: `Mozilla Add-ons Blog`)
- `meta` description
- default social image (AMO uses https://addons-amo.cdn.mozilla.net/static/b4ed07ea73fd9b86f6ace81025f9c6eb.png)

**Comment by jvillalobos** [comment]
* Title: `Firefox Add-on Reviews` (not final)
* Same `meta` description as the main site: `Download Firefox extensions and themes. They’re like apps for your browser. They can block annoying ads, protect passwords, change browser appearance, and more.`
* The default AMO uses looks good.

**Comment by vcarciu** [comment]
Verified as fixed in all major browsers.
