### ISSUE TITLE
Use addons-frontend-card package to generate the Footer

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-blog#48]
The addons-frontend-card library exposes a function to build the footer HTML
that is used on AMO. We can use it in this project, too.

---

Note: for now the addons-frontend-card library is available at
https://github.com/willdurand/addons-frontend-card and published under my npmjs
account because there are a few things to figure out in addons-frontend. It's
based on https://github.com/mozilla/addons-frontend/pull/10279.

**Comment by vcarciu** [comment]
Verified as fixed by comparing the footer with AMO-dev.
