### ISSUE TITLE
Build static add-on cards

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-blog#51]
We want to generate static add-on cards on the blog. These cards will be updated
with a JS library later (e.g., to hide them if the content is not accurate
anymore or to show an install button instead of the "Download FF" one).

Ideally, we'd have static add-on cards in preview, too.

**Comment by willdurand** [comment]
@vcarciu the mocks are here btw: https://www.figma.com/file/7FnxRoHYpyEfMOIfob423s/Non-Firefox-Download?node-id=448%3A86

**Comment by vcarciu** [comment]
Verified as fixed on all major browsers:
![addoncard](https://user-images.githubusercontent.com/1583842/114706193-57fba500-9d31-11eb-8214-5a55dc026dff.PNG)
