### ISSUE TITLE
Create a JS lib to enhance the static add-on cards

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-blog#52]
We added static add-on cards in #51. We also need a (small) JS lib to enhance these cards. The following features are required:

- remove card if add-on does not exist anymore
- check compatibility and show install button instead of download button
- wrap `mozAddonManager` to update the status of the install button

**Comment by willdurand** [comment]
@muffinresearch do you know how "far" we want to go with this? Do we want to mimic the animation during the install process, handle all the possible states, etc?

**Comment by willdurand** [comment]
> Are we going to just remove it, or display a message saying something like "This add-on is no longer available"? I imagine there will be some blog text referencing the card, so it might be weirder to just make it disappear entirely.

That was my understanding but recent mock-ups show something else now. I think we're not going to remove the card. Instead, it will be updated with an "unavailable" state.

**Comment by muffinresearch** [comment]
> @muffinresearch do you know how "far" we want to go with this? Do we want to mimic the animation during the install process, handle all the possible states, etc?

I'd say the basic install should would be the place to start. Reflecting all the states that mozAddonManager has would be nice to have, but I'd defer to @jvillalobos  to tell us what features should be considered MVP.

**Comment by jvillalobos** [comment]
I agree that handling all the installation states is more of a nice to have. The required bits are for the cards to reflect compatibility (Firefox, Mobile Firefox, non-Firefox) and add-on status. Looking at the current mocks, I think we'll need a different state for deleted add-ons, because then we won't have any data to show for them.

**Comment by willdurand** [comment]
> The required bits are for the cards to reflect compatibility (Firefox, Mobile Firefox, non-Firefox) and add-on status. Looking at the current mocks, I think we'll need a different state for deleted add-ons, because then we won't have any data to show for them.

@jvillalobos did we ask UX about that yet?

We have this state of the card, which could work for an add-on that has been removed since the last blog build:

<img width="704" alt="Screen Shot 2021-03-31 at 23 55 12" src="https://user-images.githubusercontent.com/217628/113216373-8af76080-927c-11eb-8603-3468a4e085ba.png">

Is this the state we should use for Firefox/mobile Firefox when the add-on is not compatible?

**Comment by jvillalobos** [comment]
We briefly discussed the deleted state, and Michael is going to look into that. For incompatible states, we might go with that but with different copy, but we should talk to Michael about it.

**Comment by willdurand** [comment]
This depends on https://github.com/mozilla/addons-frontend/issues/10353

**Comment by willdurand** [comment]
I am going to close this issue now since this work has begun.
