### ISSUE TITLE
Dynamic add-on cards should be updated for Android

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-blog#568]
We'll eventually allow more add-ons on Android and we will have add-ons compatible with Android that are not just the "recommended" ones. We should update the compatibility logic to remove the check on the promoted group.

**Comment by ioanarusiczki** [comment]
@willdurand 

I tested on Android with FF109.a1 - AMO stage and AMO prod 

I've noticed the presence of extensions which are not recommended. 

Installs are working as expected

![blog installs](https://github.com/mozilla/addons-blog/assets/33448286/abec0332-d155-403d-9f4d-3d3764db0914)
