### ISSUE TITLE
Switch to Node 18.x

### ISSUE THREAD

**Issue by diox** [mozilla/addons-blog#603]
Part of https://github.com/mozilla/addons/issues/1536

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDBLOG-17)

**Comment by ioanarusiczki** [comment]
@diox this has been verified by @vcarciu

**Comment by vcarciu** [comment]
Performed exploratory testing around addons blog and everything looks fine.

I will mark the issue as verified fixed.
