### ISSUE TITLE
Update favicon

### ISSUE THREAD

**Issue by diox** [mozilla/addons-blog#687]
https://github.com/mozilla/addons/issues/14951 but for the blog (which has its own copy of the favicon because it's kinda self-contained).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDBLOG-18)

**Comment by ioanarusiczki** [comment]
It's available on https://addons-dev.allizom.org/blog/

![new favicon](https://github.com/user-attachments/assets/05d37e0a-5c3d-4169-8ad7-5b405844c53b)
