### ISSUE TITLE
Use GraphQL instead of the REST API

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-blog#7]
We think it'd be a bit easier to use GraphQL rather than the REST API on the long run. This is because we have to fetch data from various endpoints in order to construct a blog post page (categories, authors, etc.) and the REST API does not seem to support an `include` feature (e.g., like JSON:API).

**Comment by muffinresearch** [comment]
@willdurand should this be closed and re-opened again when it's needed (if ever?)

**Comment by willdurand** [comment]
Yes, we can do that.

Out of curiosity: is there a problem with keeping issues open?
