### ISSUE TITLE
Re-implement author card on a blog post

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-blog#73]
It should look like this (without the red stuff, the mouse moved when I took the screenshot..):

<img width="128" alt="Screen Shot 2021-03-31 at 23 23 26" src="https://user-images.githubusercontent.com/217628/113213194-1cb09f00-9278-11eb-9668-d84f27332be8.png">

**Comment by vcarciu** [comment]
Verified as fixed in Firefox , Chrome and Safari .
