### ISSUE TITLE
Re-implement list of posts (blog template)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-blog#74]
It looks like this:

<img width="656" alt="Screen Shot 2021-03-31 at 23 26 30" src="https://user-images.githubusercontent.com/217628/113213479-8a5ccb00-9278-11eb-8406-4af3decc3462.png">

We can deal with the header and pagination in other issues.

**Comment by vcarciu** [comment]
Verified as fixed. 
We found an issue related to Safari, but we will track it in a separate issue : https://github.com/mozilla/addons-blog/issues/108
