### ISSUE TITLE
Implement grid-breaking pull-quote

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-blog#75]
The content of an article should be nicely aligned except for blockquotes. It should look like this:

<img width="443" alt="Screen Shot 2021-03-31 at 23 37 50" src="https://user-images.githubusercontent.com/217628/113214690-1e7b6200-927a-11eb-93da-51cd2c7e64fb.png">

**Comment by jvillalobos** [comment]
That isn't a normal blockquote, though, but a pull-quote. It's a quote from within the article that is being highlighted. I wonder if WP supports this kind of thing by default.

**Comment by willdurand** [comment]
From the UX meeting notes:

> [will] similar question for the blockquote. Do we want all blockquote to be like the one shown in the mock-ups? (not aligned)
> Yes ^ the idea is that they all flow outside of the grid.

🤔 

> I wonder if WP supports this kind of thing by default.

It does:

<img width="352" alt="Screen Shot 2021-04-01 at 09 14 23" src="https://user-images.githubusercontent.com/217628/113257267-a8ebb200-92ca-11eb-9a20-adb027132971.png">

**Comment by vcarciu** [comment]
Verified as fixed.
We found an issue in Safari browser and we will track it in a different bug : https://github.com/mozilla/addons-blog/issues/118
