### ISSUE TITLE
Add-on does not exist when we build the blog: what do we do?

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-blog#78]
When we build the blog (static version), we generate "static add-on cards" that look like this (currently // WIP):

![Screen Shot 2021-03-32 at 11 22 14](https://user-images.githubusercontent.com/217628/113216627-ecb7ca80-927c-11eb-83b1-33a525db7e5d.png)

This step involves an API call to get the data from AMO. What do we do if the add-on does not exist anymore?

1. abort the build, we cannot deploy a new blog version until content or add-on is fixed
2. remove the special HTML to insert an add-on card in the content, no card will appear in the blog post

**Comment by willdurand** [comment]
cc @jvillalobos

**Comment by jvillalobos** [comment]
This static card is replaced dynamically when the content is loaded in the client, correct?

If so, I would suggest one of these options:
* Have special HTML that indicates there should be a card for add-on X there, but without the static content.
* Have a static card that looks like what we show when an add-on has been deleted (pending decision on what that is).

I don't think we would stop the build for something like this, though raising some kind of internal warning would be good so we can figure out if a post should be updated.

**Comment by willdurand** [comment]
> This static card is replaced dynamically when the content is loaded in the client, correct?

It's not fully replaced, only the content will be updated.

> Have special HTML that indicates there should be a card for add-on X there, but without the static content.

This would mean skipping the insertion of the static add-on card, it's doable.

> Have a static card that looks like what we show when an add-on has been deleted (pending decision on what that is).

I guess we could do that, too, yeah.
