### ISSUE TITLE
Integrate Google Analytics

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-blog#85]
All blog pages should use Google Analytics to report visits and events, just like on AMO. We should use the same GA id as AMO so all reporting is integrated, and we should make sure that the add-on cards report the add-on installation and Firefox download events like they do on listing pages.

**Comment by willdurand** [comment]
@muffinresearch this is the first time we need some sort of per environment configuration (because of the different GA IDs). I see EW only renders the GA stuff for production but we want to do a bit more than tracking page views here so I think we'd need to introduce some config (dotenv maybe?). WDYT?

**Comment by muffinresearch** [comment]
I think you should still be able to distinguish -dev and stage from prod even if it uses the same id. For example, I don't think AMO uses different ids for different deployments.

**Comment by willdurand** [comment]
Ok, I thought we had a different tracking ID for each hosted env for some reasons.

**Comment by ioanarusiczki** [comment]
@willdurand 
1. while navigating from a card to another/page refresh the GA events are registered:

usually they look like this:

![standard navigation](https://user-images.githubusercontent.com/33448286/116990153-66f3c880-acdb-11eb-9564-18bc8f616bb9.png)

there's a different POST event too, which occurs but not so often and I could use it to check the tracking ID which is the same with all the other AMO envs, the Origin always indicated the server though (dev or stage)

![page navigation](https://user-images.githubusercontent.com/33448286/116990413-be923400-acdb-11eb-9472-25bbee2ceddb.png)

2. Installs on desktop - open the .xpi file in a new tab and the process continues from here (reason why I cannot see events for clicks), but I don't think that's the expected result. Also the install process is repeated if I click the button again (it's not warning the user that the add-on has already been installed like on Android).  I verified this with FF88(Win10) - release version

![installs on desktop](https://user-images.githubusercontent.com/33448286/116990879-67409380-acdc-11eb-9fdc-7e61faeaf2be.gif)

**Comment by willdurand** [comment]
> Installs on desktop - open the .xpi file in a new tab and the process continues from here (reason why I cannot see events for clicks), but I don't think that's the expected result. Also the install process is repeated if I click the button again (it's not warning the user that the add-on has already been installed like on Android). I verified this with FF88(Win10) - release version

I think for -dev/-stage, you need to set some prefs to get `mozAddonManager`: https://addons-frontend.readthedocs.io/en/latest/moz-addon-manager/

**Comment by ioanarusiczki** [comment]
@willdurand thanks! I have different results when I add extensions.webapi.testing
I'll check around tomorrow.

**Comment by ioanarusiczki** [comment]
@willdurand 

Addon installs:

- when addon/theme is installed the Console and the Network register the GA event 

![at install](https://user-images.githubusercontent.com/33448286/117112350-9cf38400-ad91-11eb-8505-11b9083ae0f5.gif)

- when the user cancels the install, I did not see GA events. Console registers `failed to install add-on with addonId=607454: `
- there's no Remove state so the install action can be repeated again and again (that I believe is known therefore expected).

**Comment by willdurand** [comment]
> when the user cancels the install, I did not see GA events. Console registers `failed to install add-on with addonId=607454: `

Right, there is no GA event sent in that case.

> there's no Remove state so the install action can be repeated again and again (that I believe is known therefore expected).

Expected (for now)
