### ISSUE TITLE
Rewrite links

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-blog#9]
We might need to rewrite some (absolute) links as we're using a headless WP instance and/or if we import existing content from blog.mozilla.org.

**Comment by muffinresearch** [comment]
We'll know soon enough, but I think this won't be an issue since you can define the blog site URL from the WP admin. I'd expect that setting to influence links, but that will need to be tested.

**Comment by willdurand** [comment]
> We'll know soon enough, but I think this won't be an issue since you can define the blog site URL from the WP admin. I'd expect that setting to influence links, but that will need to be tested.

Are you brave enough to update the url in the WP admin? :D

**Comment by willdurand** [comment]
> Are you brave enough to update the url in the WP admin? :D

So I actually tried that and it works okay-ish: it breaks the WP editor, which relies on the REST API. We could workaround this by forwarding the traffic from AMO back to WPEngine but that does not sound great...

I think we can simply update the content we receive from the API. It's just a domain with protocol that we want to replace so it should be fairly straightforward.

**Comment by willdurand** [comment]
> I think we can simply update the content we receive from the API. It's just a domain with protocol that we want to replace so it should be fairly straightforward.

See https://github.com/mozilla/addons-blog/pull/35
