### ISSUE TITLE
Update dimensions for single blogpost pages

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-blog#94]
The latest mocks have hints for the main dimensions: https://www.figma.com/file/7FnxRoHYpyEfMOIfob423s/Non-Firefox-Download?node-id=329%3A0.

Let's make sure we use the provided dimensions.

**Comment by ioanarusiczki** [comment]
@willdurand I don't think this is of actuality right now, but in case qa can check on anything, let me know.
